# Generated by Django 4.0.6 on 2022-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profession',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
