# Generated by Django 4.0.6 on 2022-07-23 16:49

import datetime
from django.db import migrations, models
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
                ('caption', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('url', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
    ]
