# Generated by Django 4.0.6 on 2022-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
