# Generated by Django 4.0.6 on 2022-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_likepost_delete_post2_remove_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Following', models.CharField(max_length=100)),
                ('Followers', models.CharField(max_length=100)),
            ],
        ),
    ]
