# Generated by Django 4.0.6 on 2022-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='Followers',
            new_name='user',
        ),
    ]
