# Generated by Django 4.0.6 on 2022-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_followers_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bgimage',
            field=models.ImageField(blank=True, default='bg.jpg', upload_to='bg_image'),
        ),
    ]
